var metaCardTable = {
    meta: {
        id: {},
        code: {},
        name: {},
        name1:{},
        mdm_code: {},
        mdm_pk: {},
        mdm_duplicate: {},
        mdm_seal: {},
        description: {},
        line_shortname: {},
        line_startdistrict: {},
        line_endistrict: {},
        line_stopby: {},
        line_lasttime: {},
        line_distance: {},
        line_businesstype: {},
        line_level: {},
        line_businessnature: {},
        line_institutionname: {},
        line_amount: {},
        line_daybus: {},
        line_avgday_bus: {},
        line_avgday_income: {},
        line_avgday_cust: {},
        line_competeway: {},
        line_competecar: {},
        line_carryrate: {},
        line_begtime: {},
        line_endtime: {},
        mdm_createdon: {},
        mdm_modifiedon: {},
        mdm_createdby: {},
        nc_code: {},
    }
}