var metaCardTable = {
    meta: {
        id: {},
        code: {},
        name: {},
        mdm_code: {},
        mdm_pk: {},
        mdm_duplicate: {},
        mdm_seal: {},
        description: {},
        cust_supplier_shortname: {},
        custsupplier_category: {},
        company_type: {},
        custsuptype: {},
        taxpayerid: {},
        industry: {},
        legal_person: {},
        currency: {},
        registered: {},
        website: {},
        telephone: {},
        fax: {},
        e_mail: {},
        country: {},
        province: {},
        city: {},
        county_area: {},
        postalcode: {},
        address: {},
        business_scope: {},
        qualification_information: {},
        nc_code: {},
        ht_code: {},
        wxxt_code: {},
        resourcesys: {},
    }
}